src/dbus_fast/aio/message_bus.py

See https://github.com/hbldh/bleak/issues/805

fix: ensure the underlying socket is closed on disconnect

---

src/dbus_fast/_private/marshaller.py
src/dbus_fast/message.py

Current
(dbus-fast-3DfzHv5p-py3.10) bdraco@Js-MacBook-Pro dbus-fast % python3 bench/marshall.py                   
Marshalling 1000000 bluez get managed objects messages took 21.308216833043844 seconds
After
Marshalling 1000000 bluez get managed objects messages took 13.261790999909863 seconds

feat: improve Marshaller performance

---

src/dbus_fast/aio/message_bus.py
src/dbus_fast/message_bus.py

Do not check internal callbacks with inspect as inspect is expensive and we already know they are correct

feat: improve callback performance

---

src/dbus_fast/_private/unmarshaller.py
tests/test_marshaller.py

Setup read_string as read_string_cast or
read_string_unpack based on if cast
can be used
closes #33

feat: improve unmarshall performance

---

src/dbus_fast/_private/unmarshaller.py
src/dbus_fast/signature.py

feat: speed up unmarshaller read_array

---

src/dbus_fast/aio/message_bus.py
src/dbus_fast/message_bus.py

There is still a long way to go to get mypy uncommented in the precommit

fix: more typing fixes

---

src/dbus_fast/_private/marshaller.pxd
src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py

feat: add additional cython types to the unmarshaller

---

build.py
src/dbus_fast/__init__.py
src/dbus_fast/aio/proxy_object.py
src/dbus_fast/glib/proxy_object.py
src/dbus_fast/proxy_object.py
src/dbus_fast/signature.py
src/dbus_fast/unpack.pxd
src/dbus_fast/unpack.py
tests/test_unpack_variants.py

Provides an optional cython version of unpack_variants

feat: cythonize unpack_variants

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py

feat: cythonize headers in unmarshaller

---

src/dbus_fast/_private/marshaller.pxd
src/dbus_fast/_private/marshaller.py

This is only a 6% speed up but its the first step
If we can get everything in https://github.com/Bluetooth-Devices/dbus-fast/pull/84 working we can get to 20-25%

feat: speed up aligning data during marshall

---

src/dbus_fast/_private/marshaller.pxd
src/dbus_fast/_private/marshaller.py

This is ~6% speed up marshalling

feat: speed up marshalling arrays

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py

This is only ~5% but its a tiny change

feat: improve performance of unmarshalling headers

---

src/dbus_fast/unpack.pxd
src/dbus_fast/unpack.py

feat: add cdef to unpack_variants

---

src/dbus_fast/_private/unmarshaller.py

feat: speed up empty array unmarshall

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py
src/dbus_fast/signature.py

feat: speed up unmarshaller

---

src/dbus_fast/_private/marshaller.pxd
src/dbus_fast/_private/marshaller.py

This is ~17% speed up marshalling common messages

feat: speed up marshaller and add typing

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py

feat: speed up unmarshall

---

src/dbus_fast/_private/_cython_compat.py
src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py
tests/test_marshaller.py

feat: inline cast uint32 and int16 to speed up unmarshall

---

.github/workflows/ci.yml
.readthedocs.yml
docs/requirements.txt
poetry.lock
pyproject.toml

This is a couple of cleanups for pyproject.toml. See commit messages for details.

chore: update pyproject.toml dependencies

---

src/dbus_fast/_private/marshaller.pxd
src/dbus_fast/_private/marshaller.py

This is a 7% speed up.
Added some additional cython typing

feat: speed up marshall write_string and write_variant

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py

feat: add cython def for unmarshaller read_sock for fd passing

---

src/dbus_fast/_private/marshaller.pxd
src/dbus_fast/_private/marshaller.py
src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/message.pxd
src/dbus_fast/message.py

feat: use cimports for message marshalling

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py
tests/test_marshaller.py

feat: add optimized reader for GetManagedObjects

---

.github/workflows/big_endian.yml

thanks to https://til.simonwillison.net/docker/emulate-s390x-with-qemu

chore: add big endian github workflow

---

src/dbus_fast/_private/marshaller.pxd

feat: improve cdef types for marshaller

---

src/dbus_fast/message_bus.pxd
src/dbus_fast/message_bus.py

feat: simplify creation of SendReply in message_bus

---

src/dbus_fast/message_bus.pxd
src/dbus_fast/message_bus.py

The python code is almost as slow as ALL of the readintos!

feat: speed up checking if a message needs a reply

---

src/dbus_fast/_private/unmarshaller.py

feat: speed up processing bluez passive advertisements

---

src/dbus_fast/service.py

fix: result typing in ServiceInterface._handle_signal

---

src/dbus_fast/message_bus.py

fixes
```
Traceback (most recent call last):
File "src/dbus_fast/aio/message_reader.py", line 26, in dbus_fast.aio.message_reader.build_message_reader._message_reader
File "src/dbus_fast/message_bus.py", line 807, in dbus_fast.message_bus.BaseMessageBus._process_message
File "src/dbus_fast/message_bus.py", line 861, in dbus_fast.message_bus.BaseMessageBus._process_message
File "src/dbus_fast/message_bus.py", line 83, in dbus_fast.message_bus.SendReply.__exit__
File "src/dbus_fast/message_bus.py", line 64, in dbus_fast.message_bus.SendReply._exit
AttributeError: type object Exception has no attribute _as_message
```

fix: exception handler failure when exception is not DBusError

---

src/dbus_fast/aio/message_bus.py
src/dbus_fast/aio/message_reader.py
src/dbus_fast/auth.py
src/dbus_fast/glib/message_bus.py
src/dbus_fast/introspection.py
src/dbus_fast/service.py

there were a few more places that were missing optional which is now strictly enforced with cython3

fix: more cython3 optional fixes

---

tests/test_send_reply.py

chore: add send_reply tests

---

src/dbus_fast/_private/address.py
tests/test_address_parser.py
tests/test_tcp_address.py

fix: clean up address parsing and tests

---

src/dbus_fast/aio/message_bus.py

pre-compute the serialized hello message

feat: speed up first connection when using asyncio

---

src/dbus_fast/message_bus.py
tests/service/test_standard_interfaces.py

fix: introspection bogus child paths

---

poetry.lock
pyproject.toml

https://github.com/Bluetooth-Devices/dbus-fast/pull/310#discussion_r1747614496

fix: ensure build uses cython3

---

src/dbus_fast/aio/message_bus.py

If no reply was set and the handler raises, the exception would be silently lost

fix: ensure exceptions are logged when no reply is expected

---

src/dbus_fast/message.py

We allow tuples now so we can construct tuples instead of lists as they are a bit faster

feat: improve performance of marshalling message headers

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py

feat: improve performance of unmarshalling variants

---

src/dbus_fast/constants.py

Enums never change, only resolve them once

feat: speed up marshalling messages

---

build_ext.py

first attempt failed to change the correct constant in build_ext.py

fix: reduce size of wheels

---

src/dbus_fast/message_bus.pxd
src/dbus_fast/message_bus.py
tests/service/test_methods.py

replaces and closes #390
closes #315

feat: add support for finding message handlers when interface is None

---

pyproject.toml
src/dbus_fast/aio/message_bus.py
src/dbus_fast/aio/message_reader.py
src/dbus_fast/glib/message_bus.py
src/dbus_fast/message_bus.py
src/dbus_fast/proxy_object.py

fix: multiple calls on the root logger instead of module logger

---

src/dbus_fast/_private/unmarshaller.py

feat: improve unmarshaller performance for byte strings

---

src/dbus_fast/_private/unmarshaller.pxd
src/dbus_fast/_private/unmarshaller.py

There are only two of these type and relatively common so we can use pre-constructed objects

feat: improve performance of unmarshalling boolean Variants

---

.github/workflows/ci.yml
.github/workflows/hacktoberfest.yml
.github/workflows/issue-manager.yml
.github/workflows/labels.yml

Dependabot already knows how to handle these

chore: pin github actions to specific SHAs to mitigate supply chain attacks

---

src/dbus_fast/service.pxd
tests/service/test_standard_interfaces.py

fix: correct ServiceInterface signature
