Bluetooth-Devices/dbus-fast

- src/dbus_fast/proxy_object.py
- tests/client/test_signals.py
The high level client currently does not support callbacks for signals with a varargs parameter. This adds support for that.
> feat: allow varargs callback for signals

- .github/workflows/ci.yml
- tests/client/test_properties.py
- tests/service/test_export.py
- tests/service/test_methods.py
- tests/service/test_properties.py
- tests/service/test_signals.py
- tests/service/test_standard_interfaces.py
- tests/test_aio_low_level.py
- tests/test_big_message.py
- tests/test_fd_passing.py
- tests/test_glib_low_level.py
Last build failed for confusing reasons. I suspect from the error the real reason is something not being released between tests. Adding a call to `bus.disconnect` at the end of every test which connects to the bus seems to fix it.
> fix: disconnect connected buses at end of tests

- src/dbus_fast/proxy_object.py
- tests/client/test_signals.py
Noticed in testing that the signature check on signal callbacks incorrectly handled kwargs.
1. `VAR_KEYWORD` type parameters and `KEYWORD_ONLY` type parameters with a default value should be simply ignored.
2. `KEYWORD_ONLY` type parameters without a default should always raise a `TypeError` as that callback will never work.
> feat: handle kwargs in signal callback

- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/message.py
- src/dbus_fast/message_bus.py
- Reorder matchers to have least likely first so we can reject on the first one
- Don't revalidate on unmarshall since the dbus implementation already will (not change in marshalling)
> feat: small speed ups to unmarshall message creation

- .github/workflows/ci.yml
- src/dbus_fast/aio/message_bus.py
- src/dbus_fast/message_bus.py
- tests/test_disconnect.py
Similar to https://github.com/python/cpython/blob/2a50772b63d7bc4ef97d16e9bcc53455c301b0ea/Lib/asyncio/selector_events.py?rgh-link-date=2022-09-24T02%3A51%3A37Z#L914
With this change ~99% of writes don't need to be scheduled and can happen right away so it helps quite a bit with the latency
I was able to get sub 1s connection times on my yale locks with this change
```
2022-09-23 21:25:16.427 DEBUG (MainThread) [bleak_retry_connector] Family Room Door (M1028EZ) - /org/bluez/hci3/dev_78_9C_85_08_D2_CE: Connecting (attempt: 1, last rssi: -76)
2022-09-23 21:25:16.727 DEBUG (MainThread) [bleak_retry_connector] Family Room Door (M1028EZ) - /org/bluez/hci3/dev_78_9C_85_08_D2_CE: Connected (attempt: 1, last rssi: -76)
```
Previously the best I could do was slightly > 1s
fixes #28
> feat: improve asyncio write performance

- src/dbus_fast/aio/message_bus.py
- tests/test_request_name.py
- The only calls are get_nowait, put_nowait, and empty which means deque is a better fit since we don't need thread safety here
> feat: improve writer performance with a deque

- src/dbus_fast/_private/unmarshaller.py
This is ~6% speed up but its more about refactoring so it can be reused to clear a path for #33
...but with ~23000 calls to unmarshall per minute even 6% is great since this code path  is 🔥 🔥 🔥
> feat: speed up unmarshall

- poetry.lock
- pyproject.toml
- src/dbus_fast/aio/message_bus.py
Avoids creating a task which will make it easier
to trace down races in the aio message_bus write_callback
We currently have a race (maybe destruction race) in
https://github.com/Bluetooth-Devices/dbus-fast/blob/d71f0e1fbd7282cbd78402414158545ba7176f6e/src/dbus_fast/aio/message_bus.py#L78
where somehow `self.buf` is `None`
> feat: use async_timeout instead of asyncio.wait_for

- poetry.lock
- pyproject.toml
https://github.com/Bluetooth-Devices/dbus-fast/pull/38#discussion_r980363091
> fix: loosen async-timeout pin to 3.0.0

- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/signature.py
reduces the stack depth by making a factory
to build the parsers per ctype
This is roughly a 9% reduction
> feat: improve unmarshaller performance

- src/dbus_fast/message_bus.py
- src/dbus_fast/proxy_object.py
remove slower _matches calls
These calls were re-implementing `if` statements under the hood.  Write them out instead as it much faster and we don't lose out on typing.
> feat: speed up message bus matching

- bench/unmarshall.py
- bench/unmarshall_2.py
- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/aio/message_bus.py
- src/dbus_fast/glib/message_bus.py
- src/dbus_fast/message.py
- src/dbus_fast/message_bus.py
Reuse the object to keep processing the stream instead
of creating a new one for each message
7% speed up in unmarshalling performance
5% speed up in processing subsequent messages
> feat: speed up unmarshall performance

- build.py
- src/dbus_fast/_private/marshaller.pxd
- src/dbus_fast/_private/marshaller.py
- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/_private/util.py
- src/dbus_fast/introspection.py
- src/dbus_fast/message.py
- src/dbus_fast/service.py
- src/dbus_fast/signature.pxd
- src/dbus_fast/signature.py
This is roughly at 10% improvement to the unmarshall path
> feat: add cython extension for signature

- build.py
- src/dbus_fast/message.pxd
- src/dbus_fast/message.py
This is ~6% speed up in marshalling.
> feat: add cython extension for messages

- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
These are in almost every message so it makes sense to have a cython version
This is only a 1.5% speed up though.
> feat: speed up unmarshalling int16 types

- tests/test_disconnect.py
Fixes the test closing out the underlying fd and getting python confused which lead to random failures and segfaults
> fix: disconnect race in tests

- src/dbus_fast/_private/marshaller.pxd
- src/dbus_fast/_private/marshaller.py
This is roughly a 3% speed up marshalling most messages
This is pre-work for optimizing `write_array` in https://github.com/Bluetooth-Devices/dbus-fast/pull/84
> feat: speed up marshalling variants

- src/dbus_fast/constants.py
- src/dbus_fast/signature.py
- src/dbus_fast/validators.py
One more step closer to turning on mypy in the CI
> feat: add additional typing

- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
closes #90
about 7% speed up.
The RPI3 can almost keep up with 4 adapters now.  The python overhead downline is now more expensive after this PR so likely effort needs to shift back to bleak and HA.
> feat: optimize for reading a{sv} messages and headers

- bench/unpack_variants.py
- src/dbus_fast/unpack.py
This function needs to only unpack very specific types since the data is coming from the unmarshaller. The isinstance checks are not needed here and a type check is all that is needed.  This speeds up the run by 30%
> feat: speed up unpack_variants

- src/dbus_fast/_private/unmarshaller.py
> feat: speed up unmarshaller

- bench/unmarshall_servicedata.py
- src/dbus_fast/_private/unmarshaller.pxd
- tests/test_marshaller.py
This was already well optimized but there were some pyobject conversions we can avoid which is <1%, but its good to have the test coverage.
> feat: add optimized parser for properties changed messages with service data

- src/dbus_fast/message_bus.py
- tests/client/test_methods.py
To return an error in a ServiceInterface, you raise a DBusError which is caught and translated to a message and sent over the bus. However, the context manager that catches this exception was incorrectly not sending a return value of True when the exception was handled. This caused the _message_reader() returned by build_message_reader() to log the error even though it was handled.
> fix: pass return value to SendReply.__exit__

- src/dbus_fast/_private/_cython_compat.py
- src/dbus_fast/_private/unmarshaller.py
> fix: correctly fallback to pure python when cython is missing

- src/dbus_fast/aio/message_bus.py
We now try to read a whole line at a time
since there is no risk of reading too far
ahead given that the spec says:
The first octet received by the server after the \r\n of the BEGIN command from the client must be the first octet of the authenticated/encrypted stream of D-Bus messages.
Unlike all other commands, the server does not reply to the BEGIN command with an authentication command of its own. After the \r\n of the reply to the command before BEGIN, the next octet received by the client must be the first octet of the authenticated/encrypted stream of D-Bus messages.
This avoids 26 read syscalls on average
fixes #128
> feat: speed up auth phase

- src/dbus_fast/_private/marshaller.py
This is a 5% speed up.
By writing this as a loop cython will write
__Pyx_PyByteArray_Append instead of a ~20
lines of python call stack
> feat: speed up marshall align

- src/dbus_fast/_private/marshaller.pxd
- src/dbus_fast/_private/marshaller.py
This is a 22% speed up
closes #140
> feat: speed up marshalling headers

- src/dbus_fast/signature.pxd
- src/dbus_fast/signature.py
- tests/test_signature.py
This is only a 1.5% speed up but we create a lot of these
> feat: speed up creating Variant objects

- src/dbus_fast/_private/unmarshaller.pxd
> feat: use cimports for unmarshaller Variant and Message

- src/dbus_fast/unpack.pxd
- src/dbus_fast/unpack.py
> feat: small speed up to _unpack_variants

- README.md
- docs/source/index.rst
There were still a few links incorrectly pointing back to altdesktop/python-dbus-next on GitHub.
> fix: fix remaining altdesktop links

- tests/client/test_methods.py
Seen in https://github.com/Bluetooth-Devices/dbus-fast/pull/170
> chore: disable flakey glib test on newer python

- src/dbus_fast/message_bus.py
- src/dbus_fast/service.py
When bleak is using passive scanning each message would cause a method handler to be constructed via `_make_method_handler`
Only construct them once.
> feat: only construct handlers once

- src/dbus_fast/aio/message_bus.py
- src/dbus_fast/aio/proxy_object.py
> feat: avoid enum dunder overhead in message_bus calls

- src/dbus_fast/auth.py
- tests/test_auth.py
Allows hardcoding a UID in `AuthExternal` and adds a basic test for the functionality.
Closes #188
> feat: allow hardcoding uid in auth

- src/dbus_fast/auth.py
- tests/test_auth.py
As a follow-up to #188 , this PR allows `EXTERNAL` auth without a uid as per RFC4422. If we pass `-1` as the uid, it will trigger the following auth sequence (source: https://gitlab.freedesktop.org/dbus/dbus/-/issues/195):
```
C: AUTH EXTERNAL            # I want to use EXTERNAL, but I do not
S: DATA                     # Who do you claim you are?
C: DATA                     # Whoever the kernel says I am
S: OK                       # Can't argue with that!
```
The upside of this is that when running in a user namespace (e.g. rootless docker), we don't need to know our uid mapping outside of the namespace to connect to the system dbus on the host.
> feat: add support for EXTERNAL auth without uid

- pyproject.toml
fix for breaking change in poetry https://github.com/python-poetry/poetry-core/pull/318
> fix: missing c extensions with newer poetry

- src/dbus_fast/signature.py
Variant documentation does not match the class signature since the fork from dbus-python.
It troubled me while reading the doc, so here is the (very small) fix.
> fix: corrects Variant documentation

- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
This works out to ~3.7% speed up against the unmarshall performance test
> feat: improve unmarshall performance

- .github/workflows/ci.yml
- tests/client/test_methods.py
- tests/client/test_properties.py
- tests/test_big_message.py
- tests/test_glib_low_level.py
- tests/test_request_name.py
No wheels just yet, but we will start testing with 3.12
> feat: initial cpython 3.12 support

- src/dbus_fast/service.py
another cython3 fix for incorrect typing
> fix: relax typing on _fn_result_to_body to allow Any

- .github/workflows/ci.yml
- bench/unmarshall.py
- bench/unmarshall_2.py
- bench/unmarshall_getmanagedobjects.py
- bench/unmarshall_interfaces_added.py
- bench/unmarshall_interfaces_removed.py
- bench/unmarshall_manufacturerdata.py
- bench/unmarshall_passive.py
- bench/unmarshall_servicedata.py
- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/aio/message_bus.py
- src/dbus_fast/aio/message_reader.py
- tests/test_marshaller.py
We already buffer in the unmarshaller so we shouldn't do it twice if we can avoid it when `negotiate_unix_fd` is `False`
`recvmsg` for the `negotiate_unix_fd` path did not check for `EAGAIN` or `EWOULDBLOCK` which could result in unexplained failures
This is ~33.17% speed up
> fix: avoid double buffering when using asyncio reader without negotiate_unix_fd

- .pre-commit-config.yaml
- bench/unmarshall_passive.py
- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/signature.py
> feat: optimize passive bluez message unmarshaller

- docs/source/authentication.rst
- src/dbus_fast/auth.py
- tests/test_auth.py
Pretty straightforward.  Don't think very many people use the ANONYMOUS auth, but included a line to keep backwards compatibility to not break anybody using the misspelled version.
> fix: spelling of `dbus_fast.auth.AuthAnnonymous` to `dbus_fast.auth.AuthAnonymous`

- src/dbus_fast/message.pxd
- src/dbus_fast/message.py
- src/dbus_fast/message_bus.pxd
- src/dbus_fast/message_bus.py
- src/dbus_fast/service.pxd
- src/dbus_fast/service.py
- tests/test_marshaller.py
> feat: speed up to processing bluez passive data

- src/dbus_fast/message_bus.py
We can do an `is` check here since we know it will be the dummy object is no reply is expected to speed up the check in the event no reply is expected.
The performance of the reply expected case will be a tiny bit slower but those messages are far less frequent
> fix: avoid checking if a message expects a reply twice

- src/dbus_fast/aio/message_bus.py
The queue should have been read from the left, but it was instead read from the right which meant if
the message did not send right away it was LIFO instead of FIFO
This went unnoticed because most of the time we can send immediately and it never queues
> fix: messages could be sent out of order if they had to queue

- src/dbus_fast/message_bus.py
- tests/service/test_standard_interfaces.py
Although uncommon, i saw nothing in the dbus spec forbidding sub-path matching possible parent paths.
Current implementation of Introspect assumes this is the case though resulting in path being presented where they are not for instance instrospect on `/a` returning subnodes `b` and `d` when the registered paths are `/a/b` and `/c/a/d` 
This mr tests and fixes the issue.
Note: a more efficient way to fix would have been to use [str.removeprefix](https://docs.python.org/3/library/stdtypes.html?highlight=removeprefix#str.removeprefix) but it is only available from python3.9.
> fix: subpath bad matching

- pyproject.toml
- src/dbus_fast/message_bus.pxd
- src/dbus_fast/message_bus.py
- src/dbus_fast/send_reply.py
- tests/service/test_standard_interfaces.py
- tests/test_address_parser.py
- tests/test_marshaller.py
- tests/test_send_reply.py
This is a workaround since context managers currently have an issue with Cython 3
fixes #229
> fix: avoid cythonizing SendReply

- tests/test_aio_multi_flags.py
- tests/test_glib_low_level.py
doesn't fix #239 but adds coverage for it for when we do fix it
test is currently marked as xfail since the bug isn't fixed
> chore: add test coverage for issue 239

- src/dbus_fast/__init__.py
Since the top-level `__init__.py` is always imported when any subpackage is imported, this caused both backends (glib and aio) to always be imported. This is not desirable, since it means that the glib backend will always be imported, even if the user only wants to use the aio. This wastes resources and in some cases can even cause a crash.
Fixes: https://github.com/Bluetooth-Devices/dbus-fast/issues/242
> feat!: don't import backends by default

- src/dbus_fast/_private/unmarshaller.py
We flip a lot of vars back but we are just going to overwrite them anyways so there is no need to do it twice
> feat: reduce overhead to reset between messages

- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
We would always remove it so we should skip it instead
> feat: speed up unmarshalling by skipping unused unix_fds header

- src/dbus_fast/service.pxd
- src/dbus_fast/service.py
We compare this a lot so we want to force __Pyx_PyUnicode_Equals
> feat: add cython typing for ServiceInterface.name

- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
This is a 3.5% speed up, but we can apply the same idea in a few more places
> feat: speed up unmarshalling Variants

- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/signature.py
This is a 4% speed up on interfaces added
> feat: speed up unpacking arrays

- src/dbus_fast/_private/marshaller.pxd
This is roughly a 10% speed up marshalling vs the benchmark
adds some more missing types
> feat: improve marshaller performance

- src/dbus_fast/_private/marshaller.pxd
- src/dbus_fast/_private/marshaller.py
- src/dbus_fast/service.py
- src/dbus_fast/signature.py
- tests/test_marshaller.py
- tests/test_signature.py
fixes test failures seen in https://github.com/home-assistant/supervisor/pull/4681
> feat: add support for tuples to the marshaller

- src/dbus_fast/constants.py
- tests/test_constants.py
The DBusError exception stores the error type as string. This makes the exception not directly compare to the ErrorType members (for example DBusError(ErrorType.FAILED, "").type != ErrorType.FAILED). This makes ErrorType also a string to make this comparision work.
> feat: make ErrorType enums compare as strings

- src/dbus_fast/aio/message_bus.py
- src/dbus_fast/message_bus.py
Avoid calling `_check_callback_type` when we know the callable being passed is correct since they are created internally
> fix: avoid expensive runtime inspection of known callables

- src/dbus_fast/aio/message_bus.py
- tests/test_aio_low_level.py
If we do not clear the exception retrieved flag on the disconnect future it will likely never be retrieved since wait_for_disconnect will never be called when the reply handler raises.
> fix: clear exception flag on disconnect future if its also sent to handlers

- .github/workflows/big_endian.yml
- .github/workflows/ci.yml
The dbus-run-session helper allows to run a session scoped D-Bus daemon without X11 dependency.
> feat: use dbus-run-session to drop X11 dependency

- pyproject.toml
related comment: https://github.com/Bluetooth-Devices/dbus-fast/pull/264#issuecomment-2334550288
> fix: add missing cython version pin to the build system

- src/dbus_fast/service.py
`typing.no_type_check_decorator` was never implemented in any major type checker and as such will be deprecated in Python 3.13. It's recommended to decorate functions with [`typing.no_type_check`](https://docs.python.org/3.13/library/typing.html#typing.no_type_check) instead.
https://docs.python.org/3.13/library/typing.html#typing.no_type_check_decorator
This will fix a few DeprecationWarnings for bleak:
```
/.../bleak/backends/bluezdbus/advertisement_monitor.py:63:
DeprecationWarning: 'typing.no_type_check_decorator' is deprecated and slated for removal in Python 3.15
@method()
/.../bleak/backends/bluezdbus/advertisement_monitor.py:67:
DeprecationWarning: 'typing.no_type_check_decorator' is deprecated and slated for removal in Python 3.15
@method() …
```
> fix: remove deprecated no_type_check_decorator

- src/dbus_fast/_private/unmarshaller.pxd
- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/message.pxd
- src/dbus_fast/message.py
- Headers are always a fixed set so we can store them in a positional list instead of a `dict`
> feat: speed up unmarshalling headers

- src/dbus_fast/message.pxd
- src/dbus_fast/message.py
We don't have a direct benchmark for this path yet. Its going to be faster to call the cdef than jumping back to python. The imporvement will be similar to the unmarshall side
> feat: speed up marshalling messages

- .github/workflows/ci.yml
Reverts Bluetooth-Devices/dbus-fast#355
> fix: revert avoid building wheels if a release is not made

- src/dbus_fast/introspection.py
- tests/test_introspection.py
D-Bus allow annotations in introspection data:
> ...
>
> Method, interface, property, signal, and argument elements may have
> "annotations", which are generic key/value pairs of metadata. They
> are similar conceptually to Java's annotations and C# attributes.
>
> ...
https://dbus.freedesktop.org/doc/dbus-specification.html#introspection-format
This commit add new attribute "annotations" to:
- dbus_fast.introspection.Arg
- dbus_fast.introspection.Signal
- dbus_fast.introspection.Method
- dbus_fast.introspection.Property
- dbus_fast.introspection.Interface
> feat(introspect): implement annotations

- src/dbus_fast/_private/unmarshaller.py
The loop would never be entered so it did not break but it would do some unneed dict lookups
> fix: attempting to unmarshall some arrays twice

- src/dbus_fast/_private/unmarshaller.py
Instead of calling the constprop, let cython use the new path
> feat: speed up bytearray creation in unmarshaller

- .github/workflows/ci.yml
The wheel build on `macos-latest` seems to be fine.
Tested it on my fork: https://github.com/cdce8p/dbus-fast/actions/runs/13159290301/job/36723708766
> feat: build macos arm wheels

- src/dbus_fast/constants.py
This specifically adds TimedOut which is quite often seen if a systemd managed service which uses D-Bus activation does not start in time.
> feat: resync generic D-Bus errors

- src/dbus_fast/_private/unmarshaller.pxd
- tests/test_marshaller.py
This should have been an `unsigned int` not an `unsigned long`
> fix: correct size of uint32 with cython

- tests/benchmarks/test_unmarshall.py
We only had benchmarks for reading a stream. bleak is going to use a socket most of the time
> chore: add socket unmarshall benchmark

- src/dbus_fast/_private/unmarshaller.py
Cython will write a constant set lookups the same way as multiple `==`s
> feat: simplify code to unmarshall arrays

- src/dbus_fast/_private/unmarshaller.py
- src/dbus_fast/signature.pxd
- src/dbus_fast/signature.py
- tests/test_signature.py
> feat: improve unmarshall performance for SignatureType

- README.md
👋 Noticed a couple of the links to the docs were pointing to a non-existent project (or maybe it used to be there but was changed?).
> fix: correct documentation URLs in README
